export const DexOpcodes = {
    AddLiquidityPartTon: 0x1b434676,
    AddLiquidityPartJetton: 0x64c08bfc,
    PartHasBeenDeposited: 0xe7a3475f,
    PayoutFromPool: 0x074f7a60,
    SwapRequestTon: 0x698cba08,
    SwapRequestAction: 0xbfa68001,
    SwapIn: 0xac2f5a38,
    LiquidityDeposit: 0x642b7d07,
}

export const DexErrors = {
    // ton vault errors
    SENDER_SHOULD_BE_AMM_POOL: 8952,
    NOT_ENOUGH_VALUE_FOR_FEES: 12793,
    JETTONS_SENT_TO_TON_VAULT: 39585,

    // liquidity deposit errors
    INCORRECT_LIQUIDITY_DEPOSIT_AMOUNT: 27528,
    MSG_NOT_FROM_VAULTS: 23922,
    VAULTS_MUST_BE_DIFFFERENT: 21256,
    VAULTS_MUST_BE_SORTED: 24244,

    // amm pool errors
    // swap errors
    MULTIHOP_SWAP_SENDER_MUST_BE_POOL: 8254,
    MULTIHOP_SWAP_OUT_VAULT_MUST_BE_NEXT_POOL_VAULT: 21392,
    SWAP_SENDER_MUST_BE_VAULT: 33275,
    NO_LIQUIDITY_IN_POOL: 34638,
    SWAP_TIMEOUT_EXCEEDED: 37114,
    AMOUNT_OUT_IS_LESS_THAN_LIMIT: 6674,
    INSUFFICIENT_RESERVES_FOR_EXACT_OUT_VALUE: 5596,
    INSUFFICIENT_IN_AMOUNT_FOR_EXACT_OUT_VALUE: 20503,
    // liquidity provisioning errors
    BAD_LIQUIDITY_DEPOSIT_NOTIFY_MSG_SENDER: 48988,
    BAD_LIQUIDITY_AMOUNT: 45722,
    LIQUIDITY_PROVISIONING_TIMEOUT_EXCEEDED: 62070,
    LIQUIDITY_PROVISIONING_SLIPPAGE_FAILED: 27493,
    // lp withdrawal errors
    LIQUIDITY_WITHDRAWAL_TIMEOUT_EXCEEDED: 54536,
    WITHDRAWN_LIQUIDITY_AMOUNT_IS_LESS_THAN_LIMIT: 57106,

    // jetton vault errors
    // proofs
    INVALID_STATE_INIT_PROOF: 10789,
    // actions
    SENDER_IS_NOT_THE_VAULT_JETTON_WALLET: 14041,
    // TODO: separate opcodes here
    GAS_LOW_FOR_ACTION: 14016,
}

export const LiquidityProvidersPoolFee = 3n
