name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [22]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Check broken file references in internal documentation
        uses: lycheeverse/lychee-action@v2
        with:
          args: "-n -s file --exclude-path node_modules './**/*.md'"
          output: "/dev/stdout"
          fail: true
          failIfEmpty: false

      - name: Check for yarn.lock changes
        run: git diff --exit-code yarn.lock

      - name: Check for duplicates in yarn.lock
        run: yarn deduplicate

      - name: Tolk build
        run: yarn build:tolk

      - name: Check formatting
        run: yarn fmt:check

      - name: Check spelling
        run: yarn spell:check

      - name: ESLint
        run: yarn lint:es

      - name: Type check
        run: yarn tsc --noEmit

      - name: Tolk fmt
        run: yarn fmt:tolk

      - name: Run tests
        run: yarn test
