name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [22]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install Soufflé on Ubuntu
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     sudo wget https://souffle-lang.github.io/ppa/souffle-key.public -O /usr/share/keyrings/souffle-archive-keyring.gpg
      #     echo "deb [signed-by=/usr/share/keyrings/souffle-archive-keyring.gpg] https://souffle-lang.github.io/ppa/ubuntu/ stable main" | sudo tee /etc/apt/sources.list.d/souffle.list
      #     sudo apt update
      #     sudo apt install souffle

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Check broken file references in internal documentation
        uses: lycheeverse/lychee-action@v2
        with:
          args: "-n -s file --exclude-path node_modules './**/*.md'"
          output: "/dev/stdout"
          fail: true
          failIfEmpty: false

      - name: Clone Tact repository
        uses: actions/checkout@v2
        with:
          repository: tact-lang/tact
          path: tact-upstream

      - name: Install Tact dependencies
        working-directory: ./tact-upstream
        run: yarn install

      - name: Build Tact (fast)
        working-directory: ./tact-upstream
        run: yarn build:fast

      - name: Link Tact compiler
        working-directory: ./tact-upstream
        run: yarn link

      - name: Use upstream Tact compiler in DEX project
        run: yarn link @tact-lang/compiler

      - name: Build
        run: yarn build

      # Commented, since we are working with upstream Tact, and codestyle in formatter is different there
      # - name: Run Tact formatter
      #   run: yarn tact-fmt --check ./sources

      - name: Check for yarn.lock changes
        run: git diff --exit-code yarn.lock

      - name: Check for duplicates in yarn.lock
        run: yarn deduplicate

      - name: Check formatting
        run: yarn fmt:check

      - name: Check spelling
        run: yarn spell:check

      - name: ESLint
        run: yarn lint:es

      - name: Type check
        run: yarn tsc --noEmit

      # Commented, since we are working with upstream Tact, and Misti is not compatible with it
      # - name: Run Misti
      #   run: yarn misti --min-severity medium ./tact.config.json

      - name: Run tests
        run: yarn test
